# Generated by Django 2.2 on 2020-03-30 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='url',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='url', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=50)),
                ('insta', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_url', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('user', models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
