# Generated by Django 2.2 on 2020-03-30 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_fchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fchat',
            name='friend',
        ),
        migrations.AddField(
            model_name='fchat',
            name='fuser',
            field=models.ManyToManyField(blank=True, related_name='fuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
